config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :categories do
    resources :tasks
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :description, :date_created, presence: true
  validates :description, length: { minimum:10 }
  has_many :tasks, dependent: :destroy
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, :description, :start_date, :end_date, presence: true
  validates :description, length: { minimum:10 }
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_accessor :signin

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    signin = conditions.delete(:signin)
    where(conditions)
    .where(["lower(username) = :value OR 
            lower(email) = :value", 
            { value: signin.to_s.downcase.gsub(/\s+/, '') }])
    .first
  end
       
  validates :email, :username, :password, :password_confirmation, presence: true
  validates :username, uniqueness: { case_sensitive: false }
  has_many :categories, dependent: :destroy
  has_many :tasks, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # perform a sign-up along with the signin data
    devise_parameter_sanitizer.permit(:sign_in, keys: [:signin])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, 
                                                       :last_name, 
                                                       :email, 
                                                       :username, 
                                                       :password, 
                                                       :password_confirmation])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = current_user.categories
  end

  def show
  end

  def new
    @category = current_user.categories.build
  end

  def edit
  end

  def create
    @category = current_user.categories.build(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "Category created!" }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "Category updated!" }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: "Category deleted!" }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = current_user.categories.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description, :date_created, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def update
    new_params = params.require(:user).permit(:first_name,
                                              :last_name,
                                              :email, 
                                              :username, 
                                              :current_password, 
                                              :password, 
                                              :password_confirmation)

    change_password = true
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      new_params = params.require(:user).permit(:email, :username)
      change_password = false
    end
    
    @user = User.find(current_user.id)
    is_valid = false
    
    if change_password
      is_valid = @user.update_with_password(new_params)
    else
      @user.update_without_password(new_params)
    end
    
    if is_valid
      set_flash_message :notice, :updated
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_category
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    @tasks = @category.tasks
  end

  def show
  end

  def new
    @task = @category.tasks.build
  end

  def edit
  end

  def create
    @task = @category.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to category_tasks_path(@category), notice: "Task created!" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end    

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to category_task_path(@category), notice: "Task updated!" }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :ok, location: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to category_tasks_path(@category), notice: "Task deleted!" }
      format.json { head :no_content }
    end
  end

  private

  def get_category
    @category = current_user.categories.find(params[:category_id])
  end

  def set_task
    @task = @category.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :start_date, :end_date, :accomplished, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<div class="form-group">
  <%= form_with(model: category) do |form| %>
    <% if category.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :date_created %>
      <%= form.date_field :date_created, class:'form-control' %>
      <%= form.time_field :date_created, class: 'form-control' %>
    </div>
    <div class="submit">
      <%= form.submit "Save", class:'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render 'home/dashboard' %>
<div id="category">
  <h1>Update <%= @category.name %></h1>
  <%= render 'form', category: @category %>
  <%= link_to 'Back', categories_path, class: 'btn btn-dark' %>
</div>

app/views/categories/index.html.erb
<%= render 'home/dashboard' %>
<div class="task-dashboard">
  <h1>Categories</h1>
  <p id="notice"><%= notice %></p>
  <table>
    <thead>
      <th>Name</th>
      <th>Description</th>
      <th>Date Created</th>
      <th>Time</th>
      <th colspan="4"><th>
      </thead>
    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= category.date_created.strftime("%B %d, %Y") %></td>
        <td><%= category.date_created.strftime("%I:%M %p") %></td>
        <td><%= link_to 'SHOW TASKS', category_tasks_path(category), class:'btn btn-info' %></td>
        <td><%= link_to 'EDIT', edit_category_path(category), class:'btn btn-primary' %></td>
        <td><%= link_to 'DELETE', category, method: :delete, data: { confirm: 'Delete this Category?'}, class:'btn btn-danger'%></td>
      </tr>
      <% end %>
    <tbody>
  </table>
  <br>
  <%= link_to 'Add Category', new_category_path, class:'btn btn-success' %>
</div>

app/views/categories/new.html.erb
<%= render 'home/dashboard'%>
<div id="category">
  <h4>New Category</h4>
  <%= render 'form', category: @category %>
  <%= link_to 'Back', categories_path, class: 'btn btn-dark' %>
</div>

app/views/categories/show.html.erb
<div id="category class="form-group">
  <p id="notice"><%= notice %></p>
  <div class="form-group">
    <strong>Category name:</strong>
    <%= @category.name %>
  </div>
  <div class="form-group">
    <strong>Description:</strong>
    <%= @category.description %>
  </div>
  <div class="form-group">
    <strong>Date Created:</strong>
    <%= @category.date_created %>
  </div>
  <%= link_to 'Edit', edit_category_path(@category) %>
  <br>
  <%= link_to 'Back', categories_path %>
</div>

app/views/home/_dashboard.html.erb
<nav id="home-nav" class="navbar navbar-expand-lg navbar-light fixed-top">
  <form class="form-inline float-center">
    <div class="form-control mr-sm-2">Date: <%= Date.today.strftime("%B %d, %Y") %></div>
    <div class="form-control mr-sm-2">Time: <%= Time.now.strftime("%I:%M %p") %></div>
  </form>
</nav>
<div class="wrapper d-flex">
  <div class="sidebar">
    <div class="current-user">
        Hello, <%= current_user.username %>
    </div>
      <ul class="nav flex-column" >
        <li class="nav-item">
            <a>
            <i class="fas fa-folder-open"></i>
            <%= link_to 'Show Categories', categories_path %>
            </a>
        </li>
        <li class="nav-item">
            <a>
            <i class="fas fa-id-badge"></i>
            <%= link_to 'Update Profile', edit_user_registration_path %>
            </a>
        </li>
        <li class="nav-item">
            <a>
            <i class="fas fa-sign-out-alt"></i>
            <% if user_signed_in? %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
            <% end %>
            </a>
        </li>
      </ul>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'home/dashboard' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Storify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="form-group">
  <%= form_with model: [@category, @task], local: true do |f| %>
    <p>
      <% if @task.errors.any? %>
      <ul>
        <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
    </p>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :start_date %>
      <%= f.date_field :start_date, max: task.end_date,  class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :end_date %>
      <%= f.date_field :end_date, min: task.start_date, class:'form-control' %>
    </div>
    
    <div class="submit">
      <%= f.submit "save", class:'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= render 'home/dashboard' %>
<div id="task">
  <h1>Update <%= @task.name %></h1>
  <%= render 'form', task: @task %>
  <%= form_with model: [@category, @task], local: true do |f| %>
  <div class="form-group">
      <%= f.check_box :accomplished %>
      <%= f.label :accomplished %>
  </div>
  <% end %>
  <%= link_to 'Back', category_tasks_path, class: 'btn btn-dark' %> 
</div>

app/views/tasks/index.html.erb
<%= render 'home/dashboard'%>
<div class="task-dashboard">
  <h1><%= @category.name %></h1>
  <p id="notice"><%= notice %></p>
  <table>
    <thead>
      <th>Name</th>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Accomplished</th>
      <th colspan="4"><th>
      </thead>
    <tbody>
      <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.start_date.strftime("%B %d, %Y") %></td>
        <td><%= task.end_date.strftime("%B %d, %Y") %></td>
        <td class="status"><%= task.accomplished ? 'Yes' : 'No' %></td>
        <td><%= link_to 'EDIT', edit_category_task_path(@category, task), class:'btn btn-primary' %></td>
        <td><%= link_to 'DELETE', [@category, task], method: :delete, data: { confirm: 'Remove task?' }, class:'btn btn-danger' %></td>
      </tr>
      <% end %>
    <tbody>
  </table>
  <br>
  <%= link_to 'Add Task', new_category_task_path(@category), class:'btn btn-success' %>
</div>

app/views/tasks/new.html.erb
<%= render 'home/dashboard'%>
<div id="task">
  <h1>New Task</h1>
  <%= render 'form', task: @task %>
  <%= link_to 'Back', category_tasks_path, class:'btn btn-dark' %>
</div>

app/views/tasks/show.html.erb
<%= render 'home/dashboard' %>
<div id="category" class="form-group">
  <p id="notice"><%= notice %></p>
  <div class="form-group">
    <strong>Task name:</strong>
    <%= @task.name %>
  </div>
  <div class="form-group">
    <strong>Description:</strong>
    <%= @task.description %>
  </div>
  <div class="form-group">
    <strong>Date Start:</strong>
    <%= @task.start_date.strftime("%B %d, %Y") %>
  </div>
  <div class="form-group">
    <strong>Date End:</strong>
    <%= @task.end_date.strftime("%B %d, %Y") %>
  </div>
  <%= link_to 'Back', category_tasks_path, class: 'btn btn-dark' %>
</div>